version: "3"

services:
    web:
        image: php:apache
        volumes:
            - .:/var/www/html
        ports:
            - 8080:80
            - 8443:443
    db:
        image: mysql
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD="password"
volumes:
    db_data:
        driver: local
