version: '3.7'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - pamp_db_data
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: secure_password
      MYSQL_ROOT_PASSWORD: super_secure_password
    ports:
      - 3306:3306
  web:
    depends_on:
      - db
    image: phpmyadmin:apache
    restart: always
    environment:
      MYSQL_USERNAME: docker_user
      MYSQL_ROOT_PASSWORD: secure_password
    ports:
      - 80:80
      - 443:443

volumes:
  pamp_db_data: {}
